# -*- coding: utf-8 -*-
"""codnjs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x1Ov7ZcXW44b9IR49HI94RhYhx5NC5SP
"""

!ls

!pwd

import os
os.chdir('drive/My Drive/ai-sec')

!

!git add codnjs.ipynb

!git clone https://github.com/tjdghks994/ai-security.git

from google.colab import drive
drive.mount('/content/drive')